// <auto-generated />
using Merac.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TemperaturaServer.Migrations
{
    [DbContext(typeof(MeracContext))]
    partial class MeracContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Merac.Models.Merac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Boja")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("BrojMerenja")
                        .HasColumnType("int");

                    b.Property<double>("GranicaDo")
                        .HasColumnType("float");

                    b.Property<double>("GranicaOd")
                        .HasColumnType("float");

                    b.Property<double>("Interval")
                        .HasColumnType("float");

                    b.Property<double>("MaksimalnaIzmerenaVrednost")
                        .HasColumnType("float");

                    b.Property<double>("MinimalnaIzmerenaVrednost")
                        .HasColumnType("float");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("ProsecnaIzmerenaVrednost")
                        .HasColumnType("float");

                    b.Property<double>("TrenutnaVrednost")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Meraci");
                });
#pragma warning restore 612, 618
        }
    }
}
